from datetime import datetime

iso_date = "%Y-%m-%d"
iso_datetime = "%Y-%m-%dT%H:%M:%S"

def input_with_options(question: str, options: list[str], only_upper: bool = False) -> str:
  while True:
    if only_upper:
      option = input(question).strip().upper()
    else:
      option = input(question).strip()
    invalid = "****** Invalid input option. ******"
    if option in options:
      return option
    else:
      print(invalid)

def input_date_checker(question: str, required: bool=True) -> str:
  while True:
    value = input(question).strip()
    if required or (required is False and value != ""):
      try:
        datetime.strptime(value, "%Y-%m-%d")
      except ValueError:
        print("Invalid date input, please use the ISO date format [YYYY-MM-DD].")
      else:
        return value
    else:
      return ""

def split_composed_str(string: str) -> list[str]:
  return string.strip().split("%")

def join_composed_str(array: list[str]) -> str:
  return "%".join(array)

chart_of_accounts = [
  ["1", "ASSETS"],
  ["1.1", "CURRENT ASSETS"],
  ["1.1.1", "CASH AND CASH EQUIVALENTS"],
  ["1.1.1.01", "Cash"],
  ["1.1.1.02", "Bank accounts"],
  ["1.1.2", "RESTRICTED CASH AND EQUIVALENTS"],
  ["1.1.3", "MARKETABLE SECURITIES AT FAIR VALUE"],
  ["1.1.4", "ACCOUNTS AND NOTES RECEIVABLE"],
  ["1.1.4.01", "Trade receivables"],
  ["1.1.4.02", "Related parties receivable"],
  ["1.1.4.03", "Employee receivables"],
  ["1.1.4.04", "Other receivables"],
  ["1.1.4.99", "Less: Allowance for doubtful acc."],
  ["1.1.5", "NET INVESTMENT IN LEASE"],
  ["1.1.5.01", "Gross investment in lease"],
  ["1.1.5.02", "Unearned lease income"],
  ["1.1.6", "INVENTORIES"],
  ["1.1.7", "PREPAID EXPENSES"],
  ["1.1.7.01", "Prepaid rent"],
  ["1.1.7.02", "Prepaid insurance"],
  ["1.1.8", "CONTRACT ASSETS"],
  ["1.1.8.01", "Unbilled revenue"],
  ["1.1.8.02", "Conditional receivables"],
  ["1.1.9", "OTHER CURRENT ASSETS"],
  ["1.2", "NON‑CURRENT ASSETS"],
  ["1.2.1", "ACCOUNTS AND NOTES RECEIVABLE"],
  ["1.2.2", "NET INVESTMENT IN LEASE"],
  ["1.2.2.01", "Gross investment in long-term lease"],
  ["1.2.2.02", "Unearned lease long-term income"],
  ["1.2.3", "OTHER INVESTMENTS"],
  ["1.2.3.01", "Financial assets at fair value"],
  ["1.2.3.02", "Associates and joint ventures"],
  ["1.2.4", "DEFERRED TAX ASSETS"],
  ["1.2.5", "RIGHT-OF-USE ASSETS"],
  ["1.2.6", "PROPERTY, PLANT AND EQUIPMENT NET"],
  ["1.2.6.01", "Land"],
  ["1.2.6.02", "Buildings"],
  ["1.2.6.03", "Machinery and equipment"],
  ["1.2.6.04", "Vehicles"],
  ["1.2.6.05", "Furniture and fixtures"],
  ["1.2.6.06", "Accumulated depreciation"],
  ["1.2.7", "INTANGIBLE ASSETS NET"],
  ["1.2.7.01", "Software"],
  ["1.2.7.02", "Licenses and patents"],
  ["1.2.7.03", "Other intangible assets"],
  ["1.2.7.04", "Accumulated amortization"],
  ["1.2.8", "GOODWILL"],
  ["1.2.9", "OTHER NON-CURRENT ASSETS"],
  ["2", "LIABILITIES"],
  ["2.1", "CURRENT LIABILITIES"],
  ["2.1.1", "ACCOUNTS AND NOTES PAYABLE"],
  ["2.1.1.01", "Trade payables"],
  ["2.1.1.02", "Related parties payable"],
  ["2.1.1.03", "Employee payables"],
  ["2.1.1.04", "Other payables"],
  ["2.1.2", "BORROWINGS PAYABLE"],
  ["2.1.2.01", "Bank borrowings"],
  ["2.1.2.02", "Commercial paper payable"],
  ["2.1.2.03", "Credit cards"],
  ["2.1.3", "TAX PAYABLE"],
  ["2.1.4", "LEASE LIABILITIES"],
  ["2.1.5", "CONTRACT LIABILITIES"],
  ["2.1.5.01", "Advance payable"],
  ["2.1.5.02", "Conditional payable"],
  ["2.1.9", "OTHER CURRENT LIABILITIES"],
  ["2.1.9.01", "Dividends payable"],
  ["2.2", "NON-CURRENT LIABILITIES"],
  ["2.2.1", "ACCOUNTS AND NOTES PAYABLE"],
  ["2.2.2", "BORROWINGS PAYABLE"],
  ["2.2.2.01", "Bank borrowings"],
  ["2.2.3", "LEASE LIABILITIES"],
  ["2.2.4", "DEFERRED TAX LIABILITIES"],
  ["2.2.5", "PROVISIONS"],
  ["2.2.5.01", "Warranty Provisions"],
  ["2.2.5.02", "Restructuring Provisions"],
  ["2.2.9", "OTHER NON-CURRENT LIABILITIES"],
  ["3", "EQUITY"],
  ["3.1", "SHARES"],
  ["3.1.1", "SHARE CAPITAL"],
  ["3.1.1.01", "Common shares"],
  ["3.1.1.02", "Preferred shares (non-redeemable)"],
  ["3.1.2", "SHARE PREMIUM"],
  ["3.1.3", "TREASURY SHARES"],
  ["3.4", "RESERVES"],
  ["3.4.1", "OTHER COMPREHENSIVE INCOME (OCI)"],
  ["3.4.1.01", "Foreign Currency Translation Reserve"],
  ["3.4.1.02", "Fair Value Reserve (FVOCI)"],
  ["3.4.2", "Revaluation reserve"],
  ["3.5", "ACCUMULATED RESULTS"],
  ["3.5.1", "Retained earnings/losses"],
  ["3.6", "NON-CONTROLLING INTERESTS"],
  ["4", "REVENUE"],
  ["4.1", "OPERATING REVENUE"],
  ["4.1.1", "SALES OF GOODS"],
  ["4.1.1.01", "Gross revenue"],
  ["4.1.1.02", "Less: Discounts"],
  ["4.1.1.03", "Less: Refunds and allowances"],
  ["4.1.2", "SERVICES RENDERING"],
  ["4.1.2.01", "Gross revenue"],
  ["4.1.2.02", "Less: Discounts"],
  ["4.1.2.03", "Less: Refunds and allowances"],
  ["4.1.3", "OPERATING LEASES REVENUE"],
  ["4.1.3.01", "Gross revenue"],
  ["4.1.3.02", "Less: Discounts"],
  ["4.1.3.03", "Less: Refunds and allowances"],
  ["4.1.4", "FINANCE LEASES REVENUE"],
  ["4.1.4.01", "Principal revenue"],
  ["4.1.4.02", "Less: Variable consideration"],
  ["4.1.5", "LONG-TERM CONTRACT REVENUE"],
  ["4.1.5.01", "Recognized at a point-in-time"],
  ["4.1.5.02", "Recognized over time"],
  ["4.1.5.03", "Less: Variable consideration"],
  ["4.2", "OTHER INCOME"],
  ["4.2.1", "FINANCE INCOME"],
  ["4.2.1.01", "Interest from finance leases"],
  ["4.2.1.02", "Other interest revenue"],
  ["4.2.1.03", "Dividends revenue"],
  ["4.2.2", "INCIDENTAL INCOME"],
  ["5", "EXPENSES BY NATURE"],
  ["5.1", "EMPLOYEE COSTS"],
  ["5.1.1", "SALARIES AND BENEFITS"],
  ["5.1.1.01", "Wages"],
  ["5.1.1.02", "Employee benefits"],
  ["5.1.1.03", "Employee supplies"],
  ["5.1.1.04", "Commissions"],
  ["5.1.2", "POST-EMPLOYMENT BENEFITS"],
  ["5.1.2.01", "Pensions"],
  ["5.1.2.02", "Share-based payments"],
  ["5.1.2.03", "Termination benefits"],
  ["5.2", "OTHER OPERATING COSTS"],
  ["5.2.1", "MATERIALS AND SUPPLIES"],
  ["5.2.2", "FACILITIES"],
  ["5.2.2.01", "Rent"],
  ["5.2.2.02", "Utilities"],
  ["5.2.2.03", "Maintenance"],
  ["5.2.2.04", "Property Insurance"],
  ["5.2.3", "TRANSPORT"],
  ["5.2.3.01", "Fuel"],
  ["5.2.3.02", "Repairs and maintenance"],
  ["5.2.3.03", "Vehicle insurance"],
  ["5.2.3.04", "Tolls and parking"],
  ["5.2.3.05", "Travel insurance"],
  ["5.2.3.06", "Freight charges"],
  ["5.2.4", "MARKETING"],
  ["5.2.4.01", "Digital marketing"],
  ["5.2.4.02", "Promotional events"],
  ["5.2.5", "OTHERS"],
  ["5.2.5.01", "Professional fees"],
  ["5.3", "DEPRECIATION AND AMORTIZATION"],
  ["5.3.1", "PP&E depreciation"],
  ["5.3.2", "Intangible amortization"],
  ["5.4", "IMPAIRMENT LOSSES"],
  ["5.4.1", "Goodwill impairment"],
  ["5.4.2", "PP&E impairment"],
  ["5.5", "FINANCE EXPENSE"],
  ["5.5.1", "Interest Expense"],
  ["5.5.2", "Loan Fees"],
  ["5.5.3", "Lease Interest"],
  ["5.6", "TAX EXPENSE"],
  ["5.6.1", "Current Tax"],
  ["5.6.2", "Deferred Tax"],
  ["5.9", "OTHER EXPENSES"],
  ["5.9.1", "Foreign Exchange Losses"],
  ["5.9.2", "Expected Credit Losses"],
  ["5.9.3", "Donations & Grants"],
  ["5.9.9", "Unidentified expenses"],
  ["6", "RESULT ACKNOWLEDGMENT"],
  ["6.1", "Assets variation"],
]